// Static decorative graphene lattice matching the founder-selected landing reference:
// pointy-top hexagon grid with inner cells and faint spokes, scattered highlighted
// cells with extended triangles, soft glowing vertex nodes, violet ground and vignette.
// The grid is a seamless pixel-unit tile, so cells keep one scale on every page length.
// Run explicitly to regenerate the committed asset; --check verifies reproducibility.
// No runtime generator, remote asset, time input, or unseeded randomness.
import { readFile, writeFile } from 'node:fs/promises';
let seed = 20260914;
const random = () => { seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0; return seed / 4294967296; };
const n = value => Number(value.toFixed(2));
const R = 40, COLS = 14, ROWS = 12;
const DX = Math.sqrt(3) * R, TW = COLS * DX, TH = ROWS * 1.5 * R;
const vertex = (x, y, r, i) => [x + r * Math.cos((i * 60 - 90) * Math.PI / 180), y + r * Math.sin((i * 60 - 90) * Math.PI / 180)];
const move = ([x1, y1], [x2, y2]) => `M${n(x1)} ${n(y1)}L${n(x2)} ${n(y2)}`;
const ring = (x, y, r) => Array.from({ length: 6 }, (_, i) => vertex(x, y, r, i)).map(([px, py], i) => `${i ? 'L' : 'M'}${n(px)} ${n(py)}`).join('') + 'Z';
const inside = (x, y, margin) => x > margin && x < TW - margin && y > margin && y < TH - margin;
const edges = new Map(), inner = [], spokes = [], bright = [], rays = [], nodes = new Map();
// Periodic layers include one ring of cells beyond the tile so every seam is continuous.
for (let row = -1; row <= ROWS; row++) for (let col = -1; col <= COLS; col++) {
  const x = col * DX + (((row % 2) + 2) % 2) * DX / 2, y = row * 1.5 * R;
  const v = Array.from({ length: 6 }, (_, i) => vertex(x, y, R, i));
  for (let i = 0; i < 6; i++) edges.set([v[i], v[(i + 1) % 6]].map(p => p.map(n).join(',')).sort().join('|'), move(v[i], v[(i + 1) % 6]));
  inner.push(ring(x, y, R * 0.76));
  spokes.push(move(v[0], v[2]), move(v[2], v[4]), move(v[4], v[0]), move([x - R * 0.87, y], [x + R * 0.87, y]));
  // Random accents stay wholly inside the tile so repeats never cut them at a seam.
  if (inside(x, y, R * 2.2) && random() < 0.1) {
    bright.push(ring(x, y, R));
    const big = [0, 2, 4].map(i => vertex(x, y, R * 2, i));
    rays.push(move(big[0], big[1]), move(big[1], big[2]), move(big[2], big[0]), move([x, y], [x, y - R * 1.5]), move([x - R * 1.6, y], [x + R * 1.6, y]));
  }
  for (const p of v) if (inside(p[0], p[1], 8) && random() < 0.055) nodes.set(p.map(n).join(','), p);
}
const circles = [...nodes.values()].map(([x, y]) => `<circle cx="${n(x)}" cy="${n(y)}" r="${n(2.4 + random() * 1.4)}"/>`);
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none">
<!-- Generated by scripts/generate-lattice.mjs. Decorative artwork only. -->
<defs>
<radialGradient id="ground" gradientUnits="userSpaceOnUse" cx="50%" cy="360" r="1100"><stop stop-color="#150d26"/><stop offset=".42" stop-color="#110c1d"/><stop offset="1" stop-color="#07060c"/></radialGradient>
<linearGradient id="vignette" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#040307" stop-opacity=".75"/><stop offset=".22" stop-color="#040307" stop-opacity="0"/><stop offset=".78" stop-color="#040307" stop-opacity="0"/><stop offset="1" stop-color="#040307" stop-opacity=".75"/></linearGradient>
<radialGradient id="node" cx="38%" cy="32%" r="70%"><stop stop-color="#dccdff"/><stop offset=".4" stop-color="#8e74d8"/><stop offset=".8" stop-color="#40287a"/><stop offset="1" stop-color="#1b1036"/></radialGradient>
<filter id="glow" x="-200%" y="-200%" width="500%" height="500%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="1.6"/><feMerge><feMergeNode/><feMergeNode in="SourceGraphic"/></feMerge></filter>
<pattern id="lattice" patternUnits="userSpaceOnUse" width="${n(TW)}" height="${n(TH)}">
<path d="${inner.join('')}" stroke="#2e2550" stroke-width=".6" opacity=".3"/>
<path d="${spokes.join('')}" stroke="#3a2f6a" stroke-width=".5" opacity=".22"/>
<path d="${[...edges.values()].join('')}" stroke="#3b3070" stroke-width="1" opacity=".5"/>
<path d="${rays.join('')}" stroke="#5e4f96" stroke-width="1" opacity=".28"/>
<path d="${bright.join('')}" stroke="#5a4b92" stroke-width="1.3" opacity=".4"/>
<g fill="url(#node)" filter="url(#glow)" opacity=".4">${circles.join('')}</g>
</pattern>
</defs>
<rect width="100%" height="100%" fill="url(#ground)"/>
<rect width="100%" height="100%" fill="url(#lattice)"/>
<rect width="100%" height="100%" fill="url(#vignette)"/>
</svg>
`;
const target = new URL('../public/graphene-lattice.svg', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== svg) throw new Error('Static lattice differs from its deterministic generator');
} else await writeFile(target, svg);
console.log(`Static lattice tile ${n(TW)}×${n(TH)}px: ${inner.length} cells; ${bright.length} highlighted; ${circles.length} nodes; seed 20260914.`);
