// Static decorative artwork from the founder-supplied September 2026 visual spec.
// Run explicitly to regenerate the committed asset; --check verifies reproducibility.
// No runtime generator, remote asset, time input, or unseeded randomness.
import { readFile, writeFile } from 'node:fs/promises';
let seed = 20260914;
const random = () => { seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0; return seed / 4294967296; };
const n = value => Number(value.toFixed(3));
const vertices = (x, y, radius) => Array.from({ length: 6 }, (_, i) => [n(x + radius * Math.cos(i * Math.PI / 3)), n(y + radius * Math.sin(i * Math.PI / 3))]);
const polygon = (x, y, radius) => vertices(x, y, radius).map(p => p.join(',')).join(' ');
const cells = [], edges = new Map(), points = new Map();
for (let col = 0; col < 35; col++) for (let row = 0; row < 20; row++) {
  const x = col * 48 - 16, y = row * Math.sqrt(3) * 32 + (col % 2) * Math.sqrt(3) * 16 - 24;
  const v = vertices(x, y, 32);
  for (let i = 0; i < 6; i++) {
    const a = v[i], b = v[(i + 1) % 6];
    const key = [a.join(','), b.join(',')].sort().join('|');
    edges.set(key, [a, b]);
    if (a[0] > 0 && a[0] < 1600 && a[1] > 0 && a[1] < 1000) points.set(a.join(','), a);
  }
  cells.push(`<g opacity="${n(0.15 + random() * 0.14)}"><polygon points="${polygon(x, y, 32)}" fill="#07050e" stroke="#3b1865" stroke-width="1.1" opacity=".9"/><polygon points="${polygon(x - 1.8, y - 2, 30)}" fill="url(#facet)" stroke="#8c5af3" stroke-width=".62"/><polygon points="${polygon(x - 3.4, y - 3.8, 27)}" fill="url(#lavender)" stroke="#9f74ef" stroke-width=".42" opacity=".72"/></g>`);
}
const links = [...edges.values()].filter(() => random() < 0.5).map(([a, b]) => `<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" opacity="${n(0.18 + random() * 0.16)}"/>`);
const candidates = [...points.values()].map(p => ({ p, rank: random() })).sort((a, b) => a.rank - b.rank);
const nodes = candidates.slice(0, 285).map(({ p }) => `<circle cx="${p[0]}" cy="${p[1]}" r="${n(5 + random() * 1.5)}" opacity="${n(0.08 + random() * 0.08)}"/>`);
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 1600 1000" preserveAspectRatio="xMidYMid slice" fill="none">
<!-- Generated by scripts/generate-lattice.mjs. Decorative artwork only. -->
<defs>
<radialGradient id="base" cx="50%" cy="48%" r="72%"><stop stop-color="#050409"/><stop offset=".32" stop-color="#090612"/><stop offset="1" stop-color="#050509"/></radialGradient>
<linearGradient id="facet" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#4d2680" stop-opacity=".8"/><stop offset=".38" stop-color="#1b0c34" stop-opacity=".9"/><stop offset="1" stop-color="#090613" stop-opacity=".98"/></linearGradient>
<radialGradient id="lavender"><stop stop-color="#ba91ff" stop-opacity=".48"/><stop offset=".46" stop-color="#5b2b94" stop-opacity=".17"/><stop offset="1" stop-color="#160b27" stop-opacity="0"/></radialGradient>
<radialGradient id="node" cx="34%" cy="28%" r="72%"><stop stop-color="#fff"/><stop offset=".16" stop-color="#e9ddff"/><stop offset=".46" stop-color="#a260f3"/><stop offset=".78" stop-color="#4e217f"/><stop offset="1" stop-color="#150622"/></radialGradient>
<filter id="glow" x="-150%" y="-150%" width="400%" height="400%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="3.5"/><feMerge><feMergeNode/><feMergeNode in="SourceGraphic"/></feMerge></filter>
</defs>
<rect width="1600" height="1000" fill="url(#base)"/>
<circle cx="560" cy="480" r="142" fill="url(#lavender)" opacity=".2"/>
${cells.join('\n')}
<g stroke="#7142aa" stroke-width=".65">${links.join('\n')}</g>
<g fill="url(#node)" filter="url(#glow)">${nodes.join('\n')}</g>
</svg>
`;
const target = new URL('../public/graphene-lattice.svg', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== svg) throw new Error('Static lattice differs from its deterministic generator');
} else await writeFile(target, svg);
console.log(`Static lattice: ${cells.length} layered cells; ${links.length} vertex links; ${nodes.length} glowing nodes; seed 20260914.`);
